sudo: required

services:
  - docker

before_install:
  - docker build -t digitalstudiojbg/react-test -f ./cms/Dockerfile.dev ./cms

script:
  - docker run digitalstudiojbg/react-test npm test -- --coverage

after_success:
  - docker build -t digitalstudiojbg/dc-cms ./cms
  - docker build -t digitalstudiojbg/dc-nginx ./nginx
  - docker build -t digitalstudiojbg/dc-server ./server
  - docker build -t digitalstudiojbg/dc-tablet ./tablet
  - docker build -t digitalstudiojbg/dc-touchscreen ./touchscreen
  - docker build -t digitalstudiojbg/dc-clientcms ./clientcms
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push digitalstudiojbg/dc-cms
  - docker push digitalstudiojbg/dc-nginx
  - docker push digitalstudiojbg/dc-server
  - docker push digitalstudiojbg/dc-tablet
  - docker push digitalstudiojbg/dc-touchscreen
  - docker push digitalstudiojbg/dc-clientcms

notifications:
  slack:
    secure: XQFb1wsFrwUL8D8KfGSL5GAlNSle229EGfZ/O4ymWpJh0eFhMlyzjMN0wckgW0Q5KcgFS8E/XZZNjDtKH/Deu5W/HxUaTXPahDoqS6drABO2v1IccA94FFCQlW9ppqM+jtLafU6/BrHLtiLScaU4gXQ5OdcQi8zduedahzgTZJQ6G8K6PeqmswWbGZsdM5lF4g6i8rSsnhWmdxULlDS3zRUK7LuRZVsI5+lEVADtonecFPkOXl42MSQN1TfiDyj31pFSi1a8ljFDDsEIDL0pO2AkwS8AvqttDIiWG5DY/M8JpT5bFrulqhqUi/HSbaznLQ8fGgH0Mg0v20EWO4W4YLRPDsc2H5pIeGrw5PVoP03DnNUnNYuQwcySKGtWP7HG67fHGSZ6xMtI0JwHJ/RKPp2aqoRz+TKpaI6aKERh1AjwmBBXu8EuIXV234i+yHdk1X8ffkTVzqfeWKnmt92XzuwRREZbanHL7uZFulJqOLf/9HS6yFTirSKeBAo2/cXxHQhvJBQaUuOY6u45fb4AfzUKskjaERB5U5wI3KvsmAfdXIu2XC+D+NQIhd8htaNQv5iriOZLoRiJ5pCnZooRRrkTsXXrU+X3r2jnREYnL06LcFKR/bVh1ODMNvZymEz23VGSBXFTqKHSWjiGVOi17tIpTWUjTiH9P+d9432Zpm0=

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: Platypus
  env: Platypus-env
  bucket_name: elasticbeanstalk-ap-southeast-2-626158641982
  bucket_path: Platypus
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY

branches:
  only:
  - master



 