version: '3'
services:
  server:
    build: 
      context: ./server/
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./server:/app
  cms:
    build: 
      context: ./cms/
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - /app/node_modules
      - ./cms:/app
  touchscreen:
    build: 
      context: ./touchscreen/
      dockerfile: Dockerfile.dev
    ports:
      - "7000:7000"
    volumes:
      - /app/node_modules
      - ./touchscreen:/app
  tablet:
    build: 
      context: ./tablet/
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./tablet:/app
  client_cms:
    build: 
      context: ./client_cms/
      dockerfile: Dockerfile.dev
    ports:
      - "9000:9000"
    volumes:
      - /app/node_modules
      - ./client_cms:/app
  
 